project_id = "skiwjjsrbfpldeizvufl"

[functions.ai-forecast]
verify_jwt = false

[functions.portfolio-optimizer]
verify_jwt = false

[functions.nse-market-data]
verify_jwt = false

[functions.nse-stock-search]
verify_jwt = false

[functions.nse-stock-detail]
verify_jwt = false

[functions.nse-news]
verify_jwt = false

[functions.stock-data]
verify_jwt = false

[functions.news-sentiment]
verify_jwt = false

[functions.portfolio-analysis]
verify_jwt = false
